[package]
name = "path"
version = "0.2.0"
authors = ["Kyle Clemens <jkc.clemens@gmail.com>"]

[dependencies]
clap = "2.19"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
error-chain = "0.2"
number_prefix = "0.2"
separator = "0.3"
