[package]
name = "path"
version = "1.0.0"
authors = ["Anna Clemens <git@annaclemens.io>"]
edition = "2018"

[dependencies]
clap = "2"
serde_json = "1"
anyhow = "1"
number_prefix = "0.4"
separator = "0.4"

[dependencies.serde]
version = "1"
features = ["derive"]
